# Site settings
title: "Grip: A Transcendental Aesthetics of the Psyche"
description: "From World Constraints to Fitness Interfaces to Cultural Intelligence"
author: dtp
baseurl: "/grip"
url: "https://dtrup.github.io"

# Build settings
markdown: kramdown
theme: minima

# Disable header navigation completely - empty array means show nothing
header_pages: []

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

# Include/Exclude files
exclude:
  - brainstorms
  - .claude
  - scripts
  - README.md
  - CLAUDE.md
  - PROJECT.md
  - CONTRIBUTING.md
  - SDK_FEATURES.md
  - PUBLISHING.md
  - BOOK_SUMMARY.md
  - TOC.md
  - book.config.json
  - style-guide.md
  - outlines

# Defaults
defaults:
  - scope:
      path: "chapters"
    values:
      layout: "chapter"
  - scope:
      path: ""
    values:
      layout: "default"
